# Generated by Django 4.2 on 2024-07-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdictInCart',
            new_name='ProductInCart',
        ),
    ]
