# Generated by Django 4.2 on 2024-07-28 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('preview_small', models.ImageField(blank=True, null=True, upload_to='products/small/', verbose_name='Изображение маленькое')),
                ('preview_middle', models.ImageField(blank=True, null=True, upload_to='products/middle/', verbose_name='Изображение среднее')),
                ('preview_big', models.ImageField(blank=True, null=True, upload_to='products/big/', verbose_name='Изображение большое')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='products.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
